version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: pepo_nginx
        ports:
            - 8000:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./www:/var/www/html
        depends_on:
            - php
            - mysql
        restart: always    

    php:
        build: ./php
        container_name: pepo_php
        volumes:
            - ./www:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pepo_phpmyadmin
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=pepo_mysql
        depends_on:
            - mysql
        restart: always    

    mysql:
        image: mysql
        container_name: pepo_mysql
        volumes:
            - ./mysql:/var/lib/mysql        
        environment:
            - MYSQL_DATABASE=pepo_db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=pepo_user
            - MYSQL_PASSWORD=pepo_pass
        ports:
            - 3306:3306
        restart: always
        